In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2025-11-18 10:29:12.186823: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1763458152.198667   20907 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1763458152.202212   20907 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1763458152.212414   20907 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1763458152.212423   20907 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1763458152.212424   20907 computation_placer.cc:177] computation placer alr

TensorFlow version: 2.19.1


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/home/xy/Desktop/ml/TF/tf_2.20/lib/python3.10/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
I0000 00:00:1763458261.396465   20907 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8998 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:08:00.0, compute capability: 7.5


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.5388328 ,  0.31467694,  0.8364806 , -0.34627062,  0.57152873,
         0.4415775 ,  0.43034923, -0.12873718, -0.19182171, -0.4849362 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.12903076, 0.10312017, 0.17376411, 0.05324733, 0.13331927,
        0.11707276, 0.11576559, 0.06618679, 0.06214041, 0.04635281]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.1449597)

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


I0000 00:00:1763458332.238966   21151 service.cc:152] XLA service 0x7e6040004cc0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1763458332.238979   21151 service.cc:160]   StreamExecutor device (0): NVIDIA GeForce RTX 2080 Ti, Compute Capability 7.5
2025-11-18 10:32:12.251340: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1763458332.304037   21151 cuda_dnn.cc:529] Loaded cuDNN version 90300


 163/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 934us/step - accuracy: 0.6381 - loss: 1.2322

I0000 00:00:1763458332.938944   21151 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 920us/step - accuracy: 0.9135 - loss: 0.2961
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 910us/step - accuracy: 0.9584 - loss: 0.1405
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 902us/step - accuracy: 0.9687 - loss: 0.1050
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 898us/step - accuracy: 0.9743 - loss: 0.0854
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 925us/step - accuracy: 0.9778 - loss: 0.0707


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9768 - loss: 0.0794


[0.07944019883871078, 0.9768000245094299]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.4405855e-08, 1.3500047e-09, 1.8347775e-05, 3.4423626e-03,
        7.6961224e-12, 3.1640541e-06, 1.0747860e-11, 9.9652976e-01,
        5.3654840e-06, 8.9863562e-07],
       [3.8793110e-07, 2.4908045e-06, 9.9998057e-01, 1.6175045e-05,
        2.1746072e-14, 1.4103483e-07, 5.1214791e-08, 1.5928296e-13,
        9.3595226e-08, 5.9325205e-14],
       [2.8893612e-07, 9.9973685e-01, 4.5547076e-05, 1.6745783e-07,
        9.3665367e-06, 9.7870452e-07, 2.1052932e-05, 1.7806706e-04,
        7.2367802e-06, 4.3255812e-07],
       [9.9996173e-01, 3.1798764e-09, 1.1463386e-05, 6.5832802e-07,
        7.0626260e-07, 3.9377519e-06, 1.8862636e-05, 2.1943222e-06,
        1.1435066e-08, 3.2456043e-07],
       [3.2875624e-07, 1.3205714e-09, 9.5595954e-07, 2.7584091e-09,
        9.9941337e-01, 3.0175947e-08, 1.1634265e-06, 2.2936905e-05,
        1.9135141e-08, 5.6124729e-04]], dtype=float32)>